# Generates the spike's UVSC declarations (uvsc_min.h) from a local copy of
# Keil's UVSC_C.h, so no Keil header content is ever committed to this repo.
#
# Source: Keil Application Note 198 (apnt_198.zip), see third_party/uvsc/PROVENANCE.md.
# -Source may be that zip or an extracted UVSC_C.h. Output goes to the build tree.
#
# UVSC_C.h #includes UVSOCK.h, which AN198 does not ship. So only what the spike
# calls is extracted: functions whose parameters are defined in UVSC_C.h itself or
# are scalars. Scalar typedefs from the missing UVSOCK.h are substituted:
#   xBOOL -> int                passed by value only; on x64 every scalar argument
#                               takes a full 8-byte slot, so the width doesn't matter
#   UINT  -> unsigned int       (the Windows UINT)
#   xU64  -> unsigned long long (documented as "(xU64) address")
#   UVSC_CB_DATA* -> void*      (a union holding UVSOCK_CMD; never dereferenced)
# Any other UVSOCK.h type in an extracted prototype fails the spike's compile.
param(
    [string]$Source = '',   # default below: $PSScriptRoot is empty in param defaults on PS 5.1
    [Parameter(Mandatory)][string]$Out
)
$ErrorActionPreference = 'Stop'
if (-not $Source) { $Source = Join-Path (Split-Path $PSScriptRoot) 'third_party\uvsc\apnt_198.zip' }
if (-not (Test-Path $Source)) {
    throw "UVSC_C.h source not found: $Source. Download apnt_198.zip as described in third_party/uvsc/PROVENANCE.md."
}

if ($Source -like '*.zip') {
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $zip = [IO.Compression.ZipFile]::OpenRead((Resolve-Path $Source))
    try {
        $entry = $zip.Entries | Where-Object { $_.FullName -like '*/UVSC_DLL/UVSC_C.h' } | Select-Object -First 1
        if (-not $entry) { throw "UVSC_C.h not found inside $Source" }
        $reader = New-Object IO.StreamReader($entry.Open())
        $text = $reader.ReadToEnd(); $reader.Close()
    } finally { $zip.Dispose() }
} else {
    $text = [IO.File]::ReadAllText((Resolve-Path $Source))
}

$text = [regex]::Replace($text, '/\*[\s\S]*?\*/', '')      # block and Doxygen comments
$text = [regex]::Replace($text, '//[^\r\n]*', '')          # line comments

function Need($pattern, $what) {
    $m = [regex]::Match($text, $pattern)
    if (-not $m.Success) { throw "not found in UVSC_C.h: $what" }
    $m
}
function Squash($s) { ([regex]::Replace($s, '\s+', ' ')).Trim() }
function Subst($s) {
    $s = [regex]::Replace($s, '\bxBOOL\b', 'int')
    $s = [regex]::Replace($s, '\bUINT\b', 'unsigned int')
    $s = [regex]::Replace($s, '\bxU64\b', 'unsigned long long')
    [regex]::Replace($s, '\bUVSC_CB_DATA\b', 'void')
}

$lines = @(
    '// GENERATED by scripts/gen-uvsc-min.ps1 from a local copy of Keil UVSC_C.h (AN198).'
    '// Do not edit or commit. Keil licence terms apply to this content.'
    '#pragma once'
    ''
)
foreach ($enum in 'UVSC_STATUS', 'UVSC_RUNMODE', 'UVSC_CB_TYPE') {
    $m = Need "typedef\s+enum\s+_tag_$enum\s*\{([^}]*)\}\s*$enum\s*;" "enum $enum"
    $lines += "enum $enum { $(Squash $m.Groups[1].Value) };"
}
$m = Need '#define\s+UVSC_PORT_AUTO\s+(\S+)' 'UVSC_PORT_AUTO'
$lines += "constexpr int UVSC_PORT_AUTO = $($m.Groups[1].Value);"
foreach ($cb in 'uvsc_cb', 'log_cb') {
    $m = Need "typedef\s+void\s*\(\s*\*\s*$cb\s*\)\s*\(([^)]*)\)\s*;" "callback $cb"
    $lines += "typedef void (*$cb)($(Subst (Squash $m.Groups[1].Value)));"
}
$lines += ''

$functions = 'UVSC_Version', 'UVSC_Init', 'UVSC_UnInit', 'UVSC_OpenConnection', 'UVSC_CloseConnection',
    'UVSC_GEN_UVSOCK_VERSION', 'UVSC_DBG_ENTER', 'UVSC_DBG_EXIT', 'UVSC_DBG_RESET',
    'UVSC_DBG_START_EXECUTION', 'UVSC_DBG_STOP_EXECUTION', 'UVSC_DBG_STATUS', 'UVSC_DBG_RUN_TO_ADDRESS'
foreach ($fn in $functions) {
    $m = Need "_UVSC_FUNC_\s+(\w+(?:\s*\*)?)\s+$fn\s*\(([^)]*)\)\s*;" "prototype $fn"
    $lines += "using PFN_$fn = $($m.Groups[1].Value.Trim()) (*)($(Subst (Squash $m.Groups[2].Value)));"
}

New-Item -ItemType Directory -Force (Split-Path $Out) | Out-Null
Set-Content $Out $lines -Encoding ascii
"generated $Out ($($functions.Count) functions)"
